export const designCatalog = {
  bases: {
    linea: {
      id: 'linea',
      label: 'Linea',
      modelPath: '/assets/images/base-shape/linea/model.glb',
      materials: [
        {
          id: 'gold',
          preview: '/assets/images/base-shape/linea/gold/preview.webp',
          color: '/assets/images/base-shape/linea/gold/base_color.webp',
          normal: '/assets/images/base-shape/linea/gold/normal.webp',
          metalness: '/assets/images/base-shape/linea/gold/metalness.webp',
          roughness: '/assets/images/base-shape/linea/gold/roughness.webp',
        },
        {
          id: 'book black',
          preview: '/assets/images/base-shape/linea/book_black/preview.webp',
          color: '/assets/images/base-shape/linea/book_black/base_color.webp',
          normal: '/assets/images/base-shape/linea/book_black/normal.webp',
          metalness: '/assets/images/base-shape/linea/book_black/metalness.webp',
          roughness: '/assets/images/base-shape/linea/book_black/roughness.webp',
        },
      ],
    },
    moon: {
      id: 'moon',
      label: 'Moon',
      modelPath: '/assets/images/base-shape/moon/model.glb',
      materials: [
        {
          id: 'silver',
          preview: '/assets/images/base-shape/moon/cloth_grey/preview.webp',
          color: '/assets/images/base-shape/moon/cloth_grey/base_color.webp',
          normal: '/assets/images/base-shape/moon/cloth_grey/normal.webp',
          metalness: '/assets/images/base-shape/moon/cloth_grey/metalness.webp',
          roughness: '/assets/images/base-shape/moon/cloth_grey/roughness.webp',
        },
        {
          id: 'charcoal',
          preview: '/assets/images/base-shape/moon/cloth_gold/preview.webp',
          color: '/assets/images/base-shape/moon/cloth_gold/base_color.webp',
          normal: '/assets/images/base-shape/moon/cloth_gold/normal.webp',
          metalness: '/assets/images/base-shape/moon/cloth_gold/metalness.webp',
          roughness: '/assets/images/base-shape/moon/cloth_gold/roughness.webp',
        },
      ],
    },
    axis: {
      id: 'axis',
      label: 'Axis',
      modelPath: '/assets/images/base-shape/axis/model.glb',
      materials: [
        {
          id: 'black',
          preview: '/assets/images/base-shape/axis/graphite/preview.webp',
          color: '/assets/images/base-shape/axis/graphite/base_color.webp',
          normal: '/assets/images/base-shape/axis/graphite/normal.webp',
          metalness: '/assets/images/base-shape/axis/graphite/metalness.webp',
          roughness: '/assets/images/base-shape/axis/graphite/roughness.webp',
        },
        {
          id: 'grey',
          preview: '/assets/images/base-shape/axis/cashmere_metal/preview.webp',
          color: '/assets/images/base-shape/axis/cashmere_metal/base_color.webp',
          normal: '/assets/images/base-shape/axis/cashmere_metal/normal.webp',
          metalness: '/assets/images/base-shape/axis/cashmere_metal/metalness.webp',
          roughness: '/assets/images/base-shape/axis/cashmere_metal/roughness.webp',
        },
      ],
    },
    base8: {
      id: 'base8',
      label: 'Base 8',
      modelPath: '/assets/images/base-shape/base-8/model.glb',
      materials: [
        {
          id: 'natural',
          preview: '/assets/images/base-shape/base-8/color1/preview.webp',
          color: '/assets/images/base-shape/base-8/color1/base_color.webp',
          normal: '/assets/images/base-shape/base-8/color1/normal.webp',
          metalness: '/assets/images/base-shape/base-8/color1/metalness.webp',
          roughness: '/assets/images/base-shape/base-8/color1/roughness.webp',
        },
        {
          id: 'dark',
          preview: '/assets/images/base-shape/base-8/color2/preview.webp',
          color: '/assets/images/base-shape/base-8/color2/base_color.webp',
          normal: '/assets/images/base-shape/base-8/color2/normal.webp',
          metalness: '/assets/images/base-shape/base-8/color2/metalness.webp',
          roughness: '/assets/images/base-shape/base-8/color2/roughness.webp',
        },
      ],
    },
    butterfly: {
      id: 'butterfly',
      label: 'Butterfly',
      modelPath: '/assets/images/base-shape/butterfly/model.glb',
      materials: [
        {
          id: 'light',
          preview: '/assets/images/base-shape/butterfly/color1/preview.webp',
          color: '/assets/images/base-shape/butterfly/color1/base_color.webp',
          normal: '/assets/images/base-shape/butterfly/color1/normal.webp',
          metalness: '/assets/images/base-shape/butterfly/color1/metalness.webp',
          roughness: '/assets/images/base-shape/butterfly/color1/roughness.webp',
        },
        {
          id: 'dark',
          preview: '/assets/images/base-shape/butterfly/color2/preview.webp',
          color: '/assets/images/base-shape/butterfly/color2/base_color.webp',
          normal: '/assets/images/base-shape/butterfly/color2/normal.webp',
          metalness: '/assets/images/base-shape/butterfly/color2/metalness.webp',
          roughness: '/assets/images/base-shape/butterfly/color2/roughness.webp',
        },
      ],
    },
    cradle: {
      id: 'cradle',
      label: 'Cradle',
      modelPath: '/assets/images/base-shape/cradle/model.glb',
      materials: [
        {
          id: 'gold',
          preview: '/assets/images/base-shape/cradle/champagne/preview.webp',
          color: '/assets/images/base-shape/cradle/champagne/base_color.webp',
          normal: '/assets/images/base-shape/cradle/champagne/normal.webp',
          metalness: '/assets/images/base-shape/cradle/champagne/metalness.webp',
          roughness: '/assets/images/base-shape/cradle/champagne/roughness.webp',
        },
        {
          id: 'silver',
          preview: '/assets/images/base-shape/cradle/graphite/preview.webp',
          color: '/assets/images/base-shape/cradle/graphite/base_color.webp',
          normal: '/assets/images/base-shape/cradle/graphite/normal.webp',
          metalness: '/assets/images/base-shape/cradle/graphite/metalness.webp',
          roughness: '/assets/images/base-shape/cradle/graphite/roughness.webp',
        },
      ],
    },
    curva: {
      id: 'curva',
      label: 'Curva',
      modelPath: '/assets/images/base-shape/curva/model.glb',
      materials: [
        {
          id: 'natural',
          preview: '/assets/images/base-shape/curva/champagne/preview.webp',
          color: '/assets/images/base-shape/curva/champagne/base_color.webp',
          normal: '/assets/images/base-shape/curva/champagne/normal.webp',
          metalness: '/assets/images/base-shape/curva/champagne/metalness.webp',
          roughness: '/assets/images/base-shape/curva/champagne/roughness.webp',
        },
      ],
    },
    lineaContour: {
      id: 'lineaContour',
      label: 'Linea Contour',
      modelPath: '/assets/images/base-shape/linea-contour/model.glb',
      materials: [
        {
          id: 'oak',
          preview: '/assets/images/base-shape/linea-contour/gold/preview.webp',
          color: '/assets/images/base-shape/linea-contour/gold/base_color.webp',
          normal: '/assets/images/base-shape/linea-contour/gold/normal.webp',
          metalness: '/assets/images/base-shape/linea-contour/gold/metalness.webp',
          roughness: '/assets/images/base-shape/linea-contour/gold/roughness.webp',
        },
        {
          id: 'walnut',
          preview: '/assets/images/base-shape/linea-contour/cocoa_iron/preview.webp',
          color: '/assets/images/base-shape/linea-contour/cocoa_iron/base_color.webp',
          normal: '/assets/images/base-shape/linea-contour/cocoa_iron/normal.webp',
          metalness: '/assets/images/base-shape/linea-contour/cocoa_iron/metalness.webp',
          roughness: '/assets/images/base-shape/linea-contour/cocoa_iron/roughness.webp',
        },
      ],
    },
    lineaDome: {
      id: 'lineaDome',
      label: 'Linea Dome',
      modelPath: '/assets/images/base-shape/linea-dome/model.glb',
      materials: [
        {
          id: 'oak',
          preview: '/assets/images/base-shape/linea-dome/gold/preview.webp',
          color: '/assets/images/base-shape/linea-dome/gold/base_color.webp',
          normal: '/assets/images/base-shape/linea-dome/gold/normal.webp',
          metalness: '/assets/images/base-shape/linea-dome/gold/metalness.webp',
          roughness: '/assets/images/base-shape/linea-dome/gold/roughness.webp',
        },
        {
          id: 'walnut',
          preview: '/assets/images/base-shape/linea-dome/cocoa_iron/preview.webp',
          color: '/assets/images/base-shape/linea-dome/cocoa_iron/base_color.webp',
          normal: '/assets/images/base-shape/linea-dome/cocoa_iron/normal.webp',
          metalness: '/assets/images/base-shape/linea-dome/cocoa_iron/metalness.webp',
          roughness: '/assets/images/base-shape/linea-dome/cocoa_iron/roughness.webp',
        },
      ],
    },
    thrio: {
      id: 'thrio',
      label: 'Thrio',
      modelPath: '/assets/images/base-shape/thrio/model.glb',
      materials: [
        {
          id: 'brushed metal',
          preview: '/assets/images/base-shape/thrio/color1/preview.webp',
          color: '/assets/images/base-shape/thrio/color1/base_color.webp',
          normal: '/assets/images/base-shape/thrio/color1/normal.webp',
          metalness: '/assets/images/base-shape/thrio/color1/metallic.webp',
          roughness: '/assets/images/base-shape/thrio/color1/roughness.webp',
        },
      ],
    },
    twiste: {
      id: 'twiste',
      label: 'Twiste',
      modelPath: '/assets/images/base-shape/twiste/model.glb',
      materials: [
        {
          id: 'chrome',
          preview: '/assets/images/base-shape/twiste/brass_teak/preview.webp',
          color: '/assets/images/base-shape/twiste/brass_teak/base_color.webp',
          normal: '/assets/images/base-shape/twiste/brass_teak/normal.webp',
          metalness: '/assets/images/base-shape/twiste/brass_teak/metalness.webp',
          roughness: '/assets/images/base-shape/twiste/brass_teak/roughness.webp',
        },
      ],
    },
  },

  top: {
    capsule: {
      id: 'capsule',
      label: 'Capsule',
      modelPath: '/assets/images/top-shape/capsule/model.glb',
    },
    oblong: {
      id: 'oblong',
      label: 'Oblong',
      modelPath: '/assets/images/top-shape/oblong/model.glb',
    },
    oval: {
      id: 'oval',
      label: 'Oval',
      modelPath: '/assets/images/top-shape/oval/model.glb',
    },
    rectangle: {
      id: 'rectangle',
      label: 'Rectangle',
      modelPath: '/assets/images/top-shape/rectangle/model.glb',
    },
    round: {
      id: 'round',
      label: 'Round',
      modelPath: '/assets/images/top-shape/round/model.glb',
    },
    square: {
      id: 'square',
      label: 'Square',
      modelPath: '/assets/images/top-shape/square/model.glb',
    },
  },

  topColor: {
    amaniGrey: {
      id: 'amaniGrey',
      label: 'Amani Grey',
      modelPath: '/assets/images/top-color/amani_grey/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/amani_grey/base_color.webp',
        normal: '/assets/images/top-color/amani_grey/normal.webp',
        metalness: '/assets/images/top-color/amani_grey/metalness.webp',
        roughness: '/assets/images/top-color/amani_grey/roughness.webp',
        preview: '/assets/images/top-color/amani_grey/preview.webp',
      },
    },
    anatolia: {
      id: 'anatolia',
      label: 'Anatolia',
      modelPath: '/assets/images/top-color/anatolia/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/anatolia/base_color.webp',
        normal: '/assets/images/top-color/anatolia/normal.webp',
        metalness: '/assets/images/top-color/anatolia/metalness.webp',
        roughness: '/assets/images/top-color/anatolia/roughness.webp',
        preview: '/assets/images/top-color/anatolia/preview.webp',
      },
    },
    aristocrat: {
      id: 'aristocrat',
      label: 'Aristocrat',
      modelPath: '/assets/images/top-color/aristocrat/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/aristocrat/base_color.webp',
        normal: '/assets/images/top-color/aristocrat/normal.webp',
        metalness: '/assets/images/top-color/aristocrat/metalness.webp',
        roughness: '/assets/images/top-color/aristocrat/roughness.webp',
        preview: '/assets/images/top-color/aristocrat/preview.webp',
      },
    },
    autumnBronze: {
      id: 'autumnBronze',
      label: 'Autumn Bronze',
      modelPath: '/assets/images/top-color/autumn_bronze/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/autumn_bronze/base_color.webp',
        normal: '/assets/images/top-color/autumn_bronze/normal.webp',
        metalness: '/assets/images/top-color/autumn_bronze/metalness.webp',
        roughness: '/assets/images/top-color/autumn_bronze/roughness.webp',
        preview: '/assets/images/top-color/autumn_bronze/preview.webp',
      },
    },
    calacattaBlack: {
      id: 'calacattaBlack',
      label: 'Calacatta Black',
      modelPath: '/assets/images/top-color/calacatta_black/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/calacatta_black/base_color.webp',
        normal: '/assets/images/top-color/calacatta_black/normal.webp',
        metalness: '/assets/images/top-color/calacatta_black/metalness.webp',
        roughness: '/assets/images/top-color/calacatta_black/roughness.webp',
        preview: '/assets/images/top-color/calacatta_black/preview.webp',
      },
    },
    calacattaLux: {
      id: 'calacattaLux',
      label: 'Calacatta Lux',
      modelPath: '/assets/images/top-color/calacatta_lux/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/calacatta_lux/base_color.webp',
        normal: '/assets/images/top-color/calacatta_lux/normal.webp',
        metalness: '/assets/images/top-color/calacatta_lux/metalness.webp',
        roughness: '/assets/images/top-color/calacatta_lux/roughness.webp',
        preview: '/assets/images/top-color/calacatta_lux/preview.webp',
      },
    },
    cartierGold: {
      id: 'cartierGold',
      label: 'Cartier Gold',
      modelPath: '/assets/images/top-color/cartier_gold/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/cartier_gold/base_color.webp',
        normal: '/assets/images/top-color/cartier_gold/normal.webp',
        metalness: '/assets/images/top-color/cartier_gold/metalness.webp',
        roughness: '/assets/images/top-color/cartier_gold/roughness.webp',
        preview: '/assets/images/top-color/cartier_gold/preview.webp',
      },
    },
    desertDune: {
      id: 'desertDune',
      label: 'Desert Dune',
      modelPath: '/assets/images/top-color/desert_dune/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/desert_dune/base_color.webp',
        normal: '/assets/images/top-color/desert_dune/normal.webp',
        metalness: '/assets/images/top-color/desert_dune/metalness.webp',
        roughness: '/assets/images/top-color/desert_dune/roughness.webp',
        preview: '/assets/images/top-color/desert_dune/preview.webp',
      },
    },
    elegance: {
      id: 'elegance',
      label: 'Elegance',
      modelPath: '/assets/images/top-color/elegance/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/elegance/base_color.webp',
        normal: '/assets/images/top-color/elegance/normal.webp',
        metalness: '/assets/images/top-color/elegance/metalness.webp',
        roughness: '/assets/images/top-color/elegance/roughness.webp',
        preview: '/assets/images/top-color/elegance/preview.webp',
      },
    },
    fior: {
      id: 'fior',
      label: 'Fior',
      modelPath: '/assets/images/top-color/fior/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/fior/base_color.webp',
        normal: '/assets/images/top-color/fior/normal.webp',
        metalness: '/assets/images/top-color/fior/metalness.webp',
        roughness: '/assets/images/top-color/fior/roughness.webp',
        preview: '/assets/images/top-color/fior/preview.webp',
      },
    },
    goldOnyx: {
      id: 'goldOnyx',
      label: 'Gold Onyx',
      modelPath: '/assets/images/top-color/gold_onyx/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/gold_onyx/base_color.webp',
        normal: '/assets/images/top-color/gold_onyx/normal.webp',
        metalness: '/assets/images/top-color/gold_onyx/metalness.webp',
        roughness: '/assets/images/top-color/gold_onyx/roughness.webp',
        preview: '/assets/images/top-color/gold_onyx/preview.webp',
      },
    },
    ivory: {
      id: 'ivory',
      label: 'Ivory',
      modelPath: '/assets/images/top-color/ivory/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/ivory/base_color.webp',
        normal: '/assets/images/top-color/ivory/normal.webp',
        metalness: '/assets/images/top-color/ivory/metalness.webp',
        roughness: '/assets/images/top-color/ivory/roughness.webp',
        preview: '/assets/images/top-color/ivory/preview.webp',
      },
    },
    kenya: {
      id: 'kenya',
      label: 'Kenya',
      modelPath: '/assets/images/top-color/kenya/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/kenya/base_color.webp',
        normal: '/assets/images/top-color/kenya/normal.webp',
        metalness: '/assets/images/top-color/kenya/metalness.webp',
        roughness: '/assets/images/top-color/kenya/roughness.webp',
        preview: '/assets/images/top-color/kenya/preview.webp',
      },
    },
    lucid: {
      id: 'lucid',
      label: 'Lucid',
      modelPath: '/assets/images/top-color/lucid/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/lucid/base_color.webp',
        normal: '/assets/images/top-color/lucid/normal.webp',
        metalness: '/assets/images/top-color/lucid/metalness.webp',
        roughness: '/assets/images/top-color/lucid/roughness.webp',
        preview: '/assets/images/top-color/lucid/preview.webp',
      },
    },
    magma: {
      id: 'magma',
      label: 'Magma',
      modelPath: '/assets/images/top-color/magma/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/magma/base_color.webp',
        normal: '/assets/images/top-color/magma/normal.webp',
        metalness: '/assets/images/top-color/magma/metalness.webp',
        roughness: '/assets/images/top-color/magma/roughness.webp',
        preview: '/assets/images/top-color/magma/preview.webp',
      },
    },
    montBlancTexture: {
      id: 'montBlancTexture',
      label: 'Mont Blanc Texture',
      modelPath: '/assets/images/top-color/mont_blanc_texture/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/mont_blanc_texture/base_color.webp',
        normal: '/assets/images/top-color/mont_blanc_texture/normal.webp',
        metalness: '/assets/images/top-color/mont_blanc_texture/metalness.webp',
        roughness: '/assets/images/top-color/mont_blanc_texture/roughness.webp',
        preview: '/assets/images/top-color/mont_blanc_texture/preview.webp',
      },
    },
    mossBlanc: {
      id: 'mossBlanc',
      label: 'Moss Blanc',
      modelPath: '/assets/images/top-color/moss_blanc/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/moss_blanc/base_color.webp',
        normal: '/assets/images/top-color/moss_blanc/normal.webp',
        metalness: '/assets/images/top-color/moss_blanc/metalness.webp',
        roughness: '/assets/images/top-color/moss_blanc/roughness.webp',
        preview: '/assets/images/top-color/moss_blanc/preview.webp',
      },
    },
    motherEarth: {
      id: 'motherEarth',
      label: 'Mother Earth',
      modelPath: '/assets/images/top-color/mother_earth/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/mother_earth/base_color.webp',
        normal: '/assets/images/top-color/mother_earth/normal.webp',
        metalness: '/assets/images/top-color/mother_earth/metalness.webp',
        roughness: '/assets/images/top-color/mother_earth/roughness.webp',
        preview: '/assets/images/top-color/mother_earth/preview.webp',
      },
    },
    noce: {
      id: 'noce',
      label: 'Noce',
      modelPath: '/assets/images/top-color/noce/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/noce/base_color.webp',
        normal: '/assets/images/top-color/noce/normal.webp',
        metalness: '/assets/images/top-color/noce/metalness.webp',
        roughness: '/assets/images/top-color/noce/roughness.webp',
        preview: '/assets/images/top-color/noce/preview.webp',
      },
    },
    orova: {
      id: 'orova',
      label: 'Orova',
      modelPath: '/assets/images/top-color/orova/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/orova/base_color.webp',
        normal: '/assets/images/top-color/orova/normal.webp',
        metalness: '/assets/images/top-color/orova/metalness.webp',
        roughness: '/assets/images/top-color/orova/roughness.webp',
        preview: '/assets/images/top-color/orova/preview.webp',
      },
    },
    pearlMist: {
      id: 'pearlMist',
      label: 'Pearl Mist',
      modelPath: '/assets/images/top-color/pearl_mist/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/pearl_mist/base_color.webp',
        normal: '/assets/images/top-color/pearl_mist/normal.webp',
        metalness: '/assets/images/top-color/pearl_mist/metalness.webp',
        roughness: '/assets/images/top-color/pearl_mist/roughness.webp',
        preview: '/assets/images/top-color/pearl_mist/preview.webp',
      },
    },
    pietraStone: {
      id: 'pietraStone',
      label: 'Pietra Stone',
      modelPath: '/assets/images/top-color/pietra_stone/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/pietra_stone/base_color.webp',
        normal: '/assets/images/top-color/pietra_stone/normal.webp',
        metalness: '/assets/images/top-color/pietra_stone/metalness.webp',
        roughness: '/assets/images/top-color/pietra_stone/roughness.webp',
        preview: '/assets/images/top-color/pietra_stone/preview.webp',
      },
    },
    premiumGold: {
      id: 'premiumGold',
      label: 'Premium Gold',
      modelPath: '/assets/images/top-color/premium_gold/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/premium_gold/base_color.webp',
        normal: '/assets/images/top-color/premium_gold/normal.webp',
        metalness: '/assets/images/top-color/premium_gold/metalness.webp',
        roughness: '/assets/images/top-color/premium_gold/roughness.webp',
        preview: '/assets/images/top-color/premium_gold/preview.webp',
      },
    },
    roman: {
      id: 'roman',
      label: 'Roman',
      modelPath: '/assets/images/top-color/roman/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/roman/base_color.webp',
        normal: '/assets/images/top-color/roman/normal.webp',
        metalness: '/assets/images/top-color/roman/metalness.webp',
        roughness: '/assets/images/top-color/roman/roughness.webp',
        preview: '/assets/images/top-color/roman/preview.webp',
      },
    },
    shadowWhite: {
      id: 'shadowWhite',
      label: 'Shadow White',
      modelPath: '/assets/images/top-color/shadow_white/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/shadow_white/base_color.webp',
        normal: '/assets/images/top-color/shadow_white/normal.webp',
        metalness: '/assets/images/top-color/shadow_white/metalness.webp',
        roughness: '/assets/images/top-color/shadow_white/roughness.webp',
        preview: '/assets/images/top-color/shadow_white/preview.webp',
      },
    },
    siennaBronze: {
      id: 'siennaBronze',
      label: 'Sienna Bronze',
      modelPath: '/assets/images/top-color/sienna_bronze/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/sienna_bronze/base_color.webp',
        normal: '/assets/images/top-color/sienna_bronze/normal.webp',
        metalness: '/assets/images/top-color/sienna_bronze/metalness.webp',
        roughness: '/assets/images/top-color/sienna_bronze/roughness.webp',
        preview: '/assets/images/top-color/sienna_bronze/preview.webp',
      },
    },
    skye: {
      id: 'skye',
      label: 'Skye',
      modelPath: '/assets/images/top-color/skye/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/skye/base_color.webp',
        normal: '/assets/images/top-color/skye/normal.webp',
        metalness: '/assets/images/top-color/skye/metalness.webp',
        roughness: '/assets/images/top-color/skye/roughness.webp',
        preview: '/assets/images/top-color/skye/preview.webp',
      },
    },
    storm: {
      id: 'storm',
      label: 'Storm',
      modelPath: '/assets/images/top-color/storm/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/storm/base_color.webp',
        normal: '/assets/images/top-color/storm/normal.webp',
        metalness: '/assets/images/top-color/storm/metalness.webp',
        roughness: '/assets/images/top-color/storm/roughness.webp',
        preview: '/assets/images/top-color/storm/preview.webp',
      },
    },
    tajMahal: {
      id: 'tajMahal',
      label: 'Taj Mahal',
      modelPath: '/assets/images/top-color/taj_mahal/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/taj_mahal/base_color.webp',
        normal: '/assets/images/top-color/taj_mahal/normal.webp',
        metalness: '/assets/images/top-color/taj_mahal/metalness.webp',
        roughness: '/assets/images/top-color/taj_mahal/roughness.webp',
        preview: '/assets/images/top-color/taj_mahal/preview.webp',
      },
    },
    twilight: {
      id: 'twilight',
      label: 'Twilight',
      modelPath: '/assets/images/top-color/twilight/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/twilight/base_color.webp',
        normal: '/assets/images/top-color/twilight/normal.webp',
        metalness: '/assets/images/top-color/twilight/metalness.webp',
        roughness: '/assets/images/top-color/twilight/roughness.webp',
        preview: '/assets/images/top-color/twilight/preview.webp',
      },
    },
    velvet: {
      id: 'velvet',
      label: 'Velvet',
      modelPath: '/assets/images/top-color/velvet/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/velvet/base_color.webp',
        normal: '/assets/images/top-color/velvet/normal.webp',
        metalness: '/assets/images/top-color/velvet/metalness.webp',
        roughness: '/assets/images/top-color/velvet/roughness.webp',
        preview: '/assets/images/top-color/velvet/preview.webp',
      },
    },
    velvetBlack: {
      id: 'velvetBlack',
      label: 'Velvet Black',
      modelPath: '/assets/images/top-color/velvet_black/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/velvet_black/base_color.webp',
        normal: '/assets/images/top-color/velvet_black/normal.webp',
        metalness: '/assets/images/top-color/velvet_black/metalness.webp',
        roughness: '/assets/images/top-color/velvet_black/roughness.webp',
        preview: '/assets/images/top-color/velvet_black/preview.webp',
      },
    },
    veneto: {
      id: 'veneto',
      label: 'Veneto',
      modelPath: '/assets/images/top-color/veneto/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/veneto/base_color.webp',
        normal: '/assets/images/top-color/veneto/normal.webp',
        metalness: '/assets/images/top-color/veneto/metalness.webp',
        roughness: '/assets/images/top-color/veneto/roughness.webp',
        preview: '/assets/images/top-color/veneto/preview.webp',
      },
    },
    venusVein: {
      id: 'venusVein',
      label: 'Venus Vein',
      modelPath: '/assets/images/top-color/venus_vein/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/venus_vein/base_color.webp',
        normal: '/assets/images/top-color/venus_vein/normal.webp',
        metalness: '/assets/images/top-color/venus_vein/metalness.webp',
        roughness: '/assets/images/top-color/venus_vein/roughness.webp',
        preview: '/assets/images/top-color/venus_vein/preview.webp',
      },
    },
    vintageBronze: {
      id: 'vintageBronze',
      label: 'Vintage Bronze',
      modelPath: '/assets/images/top-color/vintage_bronze/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/vintage_bronze/base_color.webp',
        normal: '/assets/images/top-color/vintage_bronze/normal.webp',
        metalness: '/assets/images/top-color/vintage_bronze/metalness.webp',
        roughness: '/assets/images/top-color/vintage_bronze/roughness.webp',
        preview: '/assets/images/top-color/vintage_bronze/preview.webp',
      },
    },
    wildForest: {
      id: 'wildForest',
      label: 'Wild Forest',
      modelPath: '/assets/images/top-color/wild_forest/model.glb',
      materials: {
        baseColor: '/assets/images/top-color/wild_forest/base_color.webp',
        normal: '/assets/images/top-color/wild_forest/normal.webp',
        metalness: '/assets/images/top-color/wild_forest/metalness.webp',
        roughness: '/assets/images/top-color/wild_forest/roughness.webp',
        preview: '/assets/images/top-color/wild_forest/preview.webp',
      },
    },
  },

  accessories: {
    aria: {
      id: 'aria',
      label: 'Aria',
      modelPath: '/assets/images/accessories/aria/model.glb',
      materials: [
        {
          id: 'color1',
          preview: '/assets/images/accessories/aria/color1/preview.webp',
          chairTopColor: '/assets/images/accessories/aria/color1/chairTopColor.webp',
          chairTopNormal: '/assets/images/accessories/aria/color1/chairTopNormal.webp',
          chairTopMetalness: '/assets/images/accessories/aria/color1/chairTopMetalness.webp',
          chairTopRoughness: '/assets/images/accessories/aria/color1/chairTopRoughness.webp',
          chairLegColor: '/assets/images/accessories/aria/color1/chairLegColor.webp',
          chairLegNormal: '/assets/images/accessories/aria/color1/chairLegNormal.webp',
          chairLegMetalness: '/assets/images/accessories/aria/color1/chairLegMetalness.webp',
          chairLegRoughness: '/assets/images/accessories/aria/color1/chairLegRoughness.webp',
        },
        {
          id: 'color2',
          preview: '/assets/images/accessories/aria/color2/preview.webp',
          chairTopColor: '/assets/images/accessories/aria/color2/chairTopColor.webp',
          chairTopNormal: '/assets/images/accessories/aria/color2/chairTopNormal.webp',
          chairTopMetalness: '/assets/images/accessories/aria/color2/chairTopMetalness.webp',
          chairTopRoughness: '/assets/images/accessories/aria/color2/chairTopRoughness.webp',
          chairLegColor: '/assets/images/accessories/aria/color2/chairLegColor.webp',
          chairLegNormal: '/assets/images/accessories/aria/color2/chairLegNormal.webp',
          chairLegMetalness: '/assets/images/accessories/aria/color2/chairLegMetalness.webp',
          chairLegRoughness: '/assets/images/accessories/aria/color2/chairLegRoughness.webp',
        },
        {
          id: 'color3',
          preview: '/assets/images/accessories/aria/color3/preview.webp',
          chairTopColor: '/assets/images/accessories/aria/color3/chairTopColor.webp',
          chairTopNormal: '/assets/images/accessories/aria/color3/chairTopNormal.webp',
          chairTopMetalness: '/assets/images/accessories/aria/color3/chairTopMetalness.webp',
          chairTopRoughness: '/assets/images/accessories/aria/color3/chairTopRoughness.webp',
          chairLegColor: '/assets/images/accessories/aria/color3/chairLegColor.webp',
          chairLegNormal: '/assets/images/accessories/aria/color3/chairLegNormal.webp',
          chairLegMetalness: '/assets/images/accessories/aria/color3/chairLegMetalness.webp',
          chairLegRoughness: '/assets/images/accessories/aria/color3/chairLegRoughness.webp',
        },
      ],
    },
    siena: {
      id: 'siena',
      label: 'Siena',
      modelPath: '/assets/images/accessories/siena/model.glb',
      materials: [
        {
          id: 'color1',
          preview: '/assets/images/accessories/siena/color1/preview.webp',
          chairTopColor: '/assets/images/accessories/siena/color1/chairTopColor.webp',
          chairTopNormal: '/assets/images/accessories/siena/color1/chairTopNormal.webp',
          chairTopMetalness: '/assets/images/accessories/siena/color1/chairTopMetalness.webp',
          chairTopRoughness: '/assets/images/accessories/siena/color1/chairTopRoughness.webp',
          chairLegColor: '/assets/images/accessories/siena/color1/chairLegColor.webp',
          chairLegNormal: '/assets/images/accessories/siena/color1/chairLegNormal.webp',
          chairLegMetalness: '/assets/images/accessories/siena/color1/chairLegMetalness.webp',
          chairLegRoughness: '/assets/images/accessories/siena/color1/chairLegRoughness.webp',
        },
        {
          id: 'color2',
          preview: '/assets/images/accessories/siena/color2/preview.webp',
          chairTopColor: '/assets/images/accessories/siena/color2/chairTopColor.webp',
          chairTopNormal: '/assets/images/accessories/siena/color2/chairTopNormal.webp',
          chairTopMetalness: '/assets/images/accessories/siena/color2/chairTopMetalness.webp',
          chairTopRoughness: '/assets/images/accessories/siena/color2/chairTopRoughness.webp',
          chairLegColor: '/assets/images/accessories/siena/color2/chairLegColor.webp',
          chairLegNormal: '/assets/images/accessories/siena/color2/chairLegNormal.webp',
          chairLegMetalness: '/assets/images/accessories/siena/color2/chairLegMetalness.webp',
          chairLegRoughness: '/assets/images/accessories/siena/color2/chairLegRoughness.webp',
        },
        {
          id: 'color3',
          preview: '/assets/images/accessories/siena/color3/preview.webp',
          chairTopColor: '/assets/images/accessories/siena/color3/chairTopColor.webp',
          chairTopNormal: '/assets/images/accessories/siena/color3/chairTopNormal.webp',
          chairTopMetalness: '/assets/images/accessories/siena/color3/chairTopMetalness.webp',
          chairTopRoughness: '/assets/images/accessories/siena/color3/chairTopRoughness.webp',
          chairLegColor: '/assets/images/accessories/siena/color3/chairLegColor.webp',
          chairLegNormal: '/assets/images/accessories/siena/color3/chairLegNormal.webp',
          chairLegMetalness: '/assets/images/accessories/siena/color3/chairLegMetalness.webp',
          chairLegRoughness: '/assets/images/accessories/siena/color3/chairLegRoughness.webp',
        },
      ],
    },
    vela: {
      id: 'vela',
      label: 'Vela',
      modelPath: '/assets/images/accessories/vela/model.glb',
      materials: [
        {
          id: 'color1',
          preview: '/assets/images/accessories/vela/color1/preview.webp',
          chairTopColor: '/assets/images/accessories/vela/color1/chairTopColor.webp',
          chairTopNormal: '/assets/images/accessories/vela/color1/chairTopNormal.webp',
          chairTopMetalness: '/assets/images/accessories/vela/color1/chairTopMetalness.webp',
          chairTopRoughness: '/assets/images/accessories/vela/color1/chairTopRoughness.webp',
          chairLegColor: '/assets/images/accessories/vela/color1/chairLegColor.webp',
          chairLegNormal: '/assets/images/accessories/vela/color1/chairLegNormal.webp',
          chairLegMetalness: '/assets/images/accessories/vela/color1/chairLegMetalness.webp',
          chairLegRoughness: '/assets/images/accessories/vela/color1/chairLegRoughness.webp',
        },
        {
          id: 'color2',
          preview: '/assets/images/accessories/vela/color2/preview.webp',
          chairTopColor: '/assets/images/accessories/vela/color2/chairTopColor.webp',
          chairTopNormal: '/assets/images/accessories/vela/color2/chairTopNormal.webp',
          chairTopMetalness: '/assets/images/accessories/vela/color2/chairTopMetalness.webp',
          chairTopRoughness: '/assets/images/accessories/vela/color2/chairTopRoughness.webp',
          chairLegColor: '/assets/images/accessories/vela/color2/chairLegColor.webp',
          chairLegNormal: '/assets/images/accessories/vela/color2/chairLegNormal.webp',
          chairLegMetalness: '/assets/images/accessories/vela/color2/chairLegMetalness.webp',
          chairLegRoughness: '/assets/images/accessories/vela/color2/chairLegRoughness.webp',
        },
        {
          id: 'color3',
          preview: '/assets/images/accessories/vela/color3/preview.webp',
          chairTopColor: '/assets/images/accessories/vela/color3/chairTopColor.webp',
          chairTopNormal: '/assets/images/accessories/vela/color3/chairTopNormal.webp',
          chairTopMetalness: '/assets/images/accessories/vela/color3/chairTopMetalness.webp',
          chairTopRoughness: '/assets/images/accessories/vela/color3/chairTopRoughness.webp',
          chairLegColor: '/assets/images/accessories/vela/color3/chairLegColor.webp',
          chairLegNormal: '/assets/images/accessories/vela/color3/chairLegNormal.webp',
          chairLegMetalness: '/assets/images/accessories/vela/color3/chairLegMetalness.webp',
          chairLegRoughness: '/assets/images/accessories/vela/color3/chairLegRoughness.webp',
        },
      ],
    },
  },
} as const;

